import tkinter as tk
from tkinter import ttk

# ============ COLOR CONFIGURATION ============
COLOR_NEGRO = "#000000"
COLOR_GRIS = "#404040"
COLOR_BLANCO = "#ffffff"
COLOR_AZUL = "#4a9eff"
COLOR_VERDE = "#4caf50"
COLOR_ROJO = "#f44336"

# ============ CONFIGURACIÓN DE UI ============
# ESCALADO MULTIPLICATIVO
BASE_FONT_MULTIPLIER = 0.016  #se multiplica por altura de pantalla
#Dimension botones
BUTTON_RELWIDTH = 0.22
BUTTON_RELHEIGHT = 0.14
BUTTON_PADDING = 10

#Dimension de los frames
MENU_FRAME_RELWIDTH = 0.18
MENU_FRAME_RELHEIGHT = 0.12
MENU_FRAME_RELX = 0.2
MENU_FRAME_RELY = 0.65

#Coordenadas botones
BUTTON_SIMULACION_POS = (0.2, 0.88)      # (relx, rely)
BUTTON_TRENES_POS = (0.5, 0.88)
BUTTON_ESTACIONES_POS = (0.8, 0.88)

#Boton salir
EXIT_BUTTON_RELX = 0.98
EXIT_BUTTON_RELY = 0.02
EXIT_BUTTON_RELWIDTH = 0.08
EXIT_BUTTON_RELHEIGHT = 0.06