import tkinter as tk
from tkinter import ttk

#VARIABLES COLORES

COLOR_NEGRO ="#000000"
COLOR_GRIS = "#404040"
COLOR_BLANCO = "#ffffff"
COLOR_AZUL = "#4a9eff"
COLOR_VERDE = "#4caf50"
COLOR_ROJO = "#f44336"

#VARIABLES VENTANAS

ANCHO_VENTANA = 800
ALTO_VENTANA = 600
ANCHO_MIN_VENTANA = 400
ALTO_MIN_VENTANA = 300
PADDING_P = 10
PADDING_G = 20

#VARIABLES TEXTO

FUENTE_ARIAL_G= ("Arial", 16, "bold")
FUENTE_ARIAL_P = ("Arial", 10)